language: r
cache:
  packages: true
  directories:
  - "$TRAVIS_BUILD_DIR/_bookdown_files"
sudo: false
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  _deploy.sh
env:
  global:
  - secure: 
r_github_packages:
- bayespulse/pulsatile
env:
  global:
  - secure: zdva0qFzn2BEtv7u9UhBSnYgQ7LOFwlWZB5cb5bKpSaDrqOG2p+zjgNpgrGcetAGDfd8z3LHrsuBfSIIpN4R8URaIi1fxDjMADsDiGgLCqy3u+m03dHb6XVFW8tHLCnUOn3oM+cdBRuJ6oY+AOH0VZd/9mP8KqqCJBfVtW7NpGhosOKsRDbBsJc6xTWFZZK0zUOD3O4ajADqhMA6eQoXaqo+TGBcQQhSQU73KaLVsYde0e/M1nzdIjm0KAYfT79BQjru8PbXJ/Cp0cAcSKfIFWeEkrnl9upBGBVNjAXtc5EAtJUYaNI58RJaWcsoAOEN3y0N+O2jryAizILroo6CUcBSkU8VLUPzQIyQLQC2DxnW/Luvvagbo8bwq4elHRepGM5iF7vDnufY9KFhnxFb7YN6+PlZU5cMfMbb8/QOTsxGzwAQ66I4YHgdRyGIrGhwc4vroSqcR1RlcSx+rn9ncz+L+HqJJZCmsI/NDIKeB8HsG9FdrNL1YxSpStw5HXky+pQKtQntr/p4zAI/NPcTUb88qqNplS081aGXDnseeS7PfErHgsVuXxfcjMW/TJGYirhqm4kw0Mby6QuNZbUbF53Iq7WD+VCIo4CmXPkGqT+ZY6I9/4W6FB/x6yVRbId+zuTH924h+SNTNpAy0zR2MGR8Edf++mYgpnQ66BF2Wto=
