language: r
cache: packages
pandoc_version: 1.19.2.1
sudo: false

env:
  global: 
    - secure: I4tAoezhVC1EjF3kgFsk1qRmN0puaiXn/CO34hiuX97rnDjjOC6jfmrZxRP3WVS4uItZtHXiUEpekvk+WoSMGEhHqiJi4GE4/TrhLg3myl5tWFKAu0BSQw43hgFQjZyHUOyAL0H7viVehug+a5v7KgHAKuPdKMK7MD/42NVO19p5E+bwR9vsTo30WeOWGKO3onjMxksJhSxwCI6nq+ABoY8jo2JVwUfUOwF3Zgh1xpxQyseGWn31OhC6Ckp2MiQwairSk1rv1ipzuNlGhq3UgR32GVZ0zDCfiD2yinM3sLfrgqu2rBF08Eim8XGPkmzJN0ZezpseWipPw2Xgo8Tt7rmCWlxlaEPnu4SMYVwQWt6zhtb4nikdHKe8RVMI3I+WlJyxSuG5TLlw9cE5la85mSITWD/MTQkiqu1e3OvbdEPIxmJTgnmaFywqaHPSKHTHHGhCwG01SRFeYYf9lFLFaajCZeHiySPdvm55dRRHEIJjuPtPyBfa5CbIb8zpidua8I/A/S/fiTlVUkHiGW4ZQR2UppEsq1XsIeK3adh8LsgkYIv0z2RExnnPU0NmjKok1aWZHGXzd7dvuORUkr5AFOUiemiwcJ7YapkXMPKkGM/61yPF8NtfcojX4/18Jm4rfyjt9njywEi6FVeNUb7BUHyo8Q20i3xSuwAhRMWNp+k=

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - "./_build.sh"
  - "./_deploy.sh"

