language: r
cache: packages
pandoc_version: 1.19.2.1
sudo: false

env:
  global: 
    - secure: BjYJquq76fCvR8vET8boR2wJIwQRoVSS16bu6itVcserHA9rMUaRsDo0AHZYWz2majZI2P5PyJ13Alr+PKG29VZZkOXla5z3GcimH8Xbd08GnrFi4Ig2+j00fcEhsziWdydOEF2h/2r7DWJFYLYa2MtqagwmSkDk6usvi36HVRYeC7LO433bcUl+2Zh4OxRyKFVC1j1pDw4paX3mh3KoxlDUUJ/koVfAD0hKv1b02SKuv8M+Ul9gupEZg6b/oVsofuXSzPzziZrhaSWKrrIyD6eLpE7ocsAS0q65sZ1GRHJJVC7qeaibbODsK0itgZTCZDnx89klsFTQuyIzeFIh337LsXlAS0F5uQE8I57YtL9xZS8rngDSvarlKSYX2164pF3Y92pA9U8h4thy2mN6yqAlw6uZP+hvd2dHes9y4RGph30HhS6AbEOtcVxi12CBXzxDos+8x3MXH8gk65GSCODYXH6EOMEK9k8MiSdMb2lvWKO4C3B94Jri5W4Zi2jJtu4IXofqZGecnQo6eutr8APGvNKQfokVzkv0lWAVhobMQIJQ5/uL/InsQOZA4eZ6TkhFIpd99wzpJawo3qaD3dMnVwGgZqsz8yF7aQ+VB6+0d4uK6jT2v8lr37CvdlXy3M/ed94+GOykltrozPLuuHbJdveOQRk2OzCeyqzct5o=

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - "./_build.sh"
  - "./_deploy.sh"

