language: r
cache: packages
pandoc_version: 1.19.2.1
sudo: false

env:
  global: 
    - secure: oaGGOkUiCT+sgqfdWtM2PYyLUrgFqu6qDmmcdITCElDarf83ZZig3atvXosZWy/bGB3vAWzUgPXfhOmoh8LxApvJX8o2ejBCxf+9Sc16i/bAu1hDrOx9Hn46BR9rN9KgPmFZqpidAcRcp3c3PJWxWw8pSiuxV7C8tL3+XfHVCiewgoTn8jPh0NA8vMr3IDDw21vGBfTZcZvqvmCAsDIVVgXBvDfY1TKRhl8+iZchBTiYRdVz1EIMHhJ8L5gwIQgbCYagLmRYv8Y1TJd+qYVDi+wTNfIoofrGVnow2++1X6MvCCalVUHdet9sWtVWOIiqHV2o5QMLtmQYQPu8f6H/7SPzYXs7FLPEgNZXl6/F/1AQI9perhu24ez+49kdWQwsqNWYk/B4YdwlyQbKKSBGECidZszq5b+4x0Tex+fosj4uDmYunhNyjghY92lb48tiKptamSYa/h40bXCA2hm7xRkesO5DFfRy5U2biw3DGrKcXZUSShwkSSzhZ5tZ1rOFwXKJSgOYLvhpAp0hJBa1STbmefBCv2FPjRDq3hVpO3+08/Q5kAucp1/390GZTnDKZAiAKdqaCDDBdNSCm7Wp1+Ya5HVnmMW6VoGrbTJgAczXwfVsbVDScIvbkmwICWzPwr1fUljgR/QBeugEFOdekCR/p5rc19kMsTGhWAQMVv8=

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - "./_build.sh"
  - "./_deploy.sh"

