# Directory Structure and File Naming Standards

General file naming standards:

- Use CamelCode for the study name (e.g. StatinDiscontinuationStudyRCTData)
- Study instruments (forms) should be numbered in the chronological order
  administered, followed by a descriptive name.  If a code or numbering system
  was used during the study, this can follow the number and descriptive
  name: 01\_Eligibility\_SDSRCT01.pdf
- Use underscores or hyphens to separate information in filenames. Do not use
  spaces within filenames.  

Structure: 

1. Study name
    1. Code
        a. Data cleaning
        b. Analysis dataset generation (if applicable)
        c. Descriptive and Primary Analysis
    1. Data
        a. Raw
        a. Clean
        a. Analysis (if applicable)
    1. Documentation
        a. Raw dataset dictionary
        a. Clean dataset dictionay
        a. Study Tools/Instruments
    1. Protocols
        a. Study Protocol (PDF)
    1. Publications
        a. Bibtex file of references for all publications based on study,
           including url/uri to online location
        a. PDF for articles that can be opening shared
    1. Reports
        a. Summary and Statistical Reports

