#print draws of all parameters

postscript("F:/Nichole/K12/software_info/allpara.ps")
par(mfrow=c(3,4))

burnin<-401
nn<-50

titles<-c("Npulses","driverbasal","respbasal","driverdecay","respdecay","drivermwidth","respmwidth","alphalag","betalag","drivermmass","respmmass","driverc0","respc0","LogLikelihood","invdrivererror","invresperror","correrr","dmasserr","rmasserr","masscorr","dvarerr","rvarerr","corrvar")

data<-read.table(paste("E:/Bivariate_BDMCMC/Bivariate_paper_revisions/bivariate_BDMCMC_analysis/lhfsh/c",sep="",j,".out"),col.names=c("Npulses","driverbasal","respbasal","driverdecay","respdecay","drivermwidth","respmwidth","alphalag","betalag","drivermmass","respmmass","driverc0","respc0","LogLikelihood","invdrivererror","invresperror","correrr","dmasserr","rmasserr","masscorr","dvarerr","rvarerr","corrvar"))
data<-data[burnin:length(data[,1]),]

pdata<-read.table(paste("E:/Bivariate_BDMCMC/Bivariate_paper_revisions/bivariate_BDMCMC_analysis/lhfsh/p",sep="",j,".out"),col.names=c("iter","Npulse","pnumb","driverloc","drivermass","dwidth","resploc","respmass","rwidth","lag","eta1","eta2"))

pdata<-pdata[pdata$iter>=burnin*nn,]

ts.plot(data$Npulses,main="Number of Pulses")
hist(data$Npulses,main="Number of Pulses")
mean1<-mean(data$Npulses)
var1<-var(data$Npulses)
quant<-quantile(data$Npulses,c(0.05,0.5,0.95))


ts.plot(data[,2]*data[,4]/log(2),main=paste("Driver Baseline",sep="",j))
hist(data[,2]*data[,4]/log(2),main=paste("Driver Baseline",sep="",j))
mean1<-mean(data[,2]*data[,4]/log(2))
print("mean of driver baseline distribution")
print(mean1)
var1<-var(data[,2]*data[,4]/log(2))
print(var1)
quant<-quantile(data[,2]*data[,4]/log(2),c(0.05,0.5,0.95))
print(quant)

ts.plot(data[,3]*data[,5]/log(2),main=paste("Resp Baseline",sep="",j))
hist(data[,3]*data[,5]/log(2),main=paste("Resp Baseline",sep="",j))
mean1<-mean(data[,3]*data[,5]/log(2))
print("mean of response baseline distribution")
print(mean1)
var1<-var(data[,3]*data[,5]/log(2))
print(var1)
quant<-quantile(data[,3]*data[,5]/log(2),c(0.05,0.5,0.95))
print(quant)

ts.plot(data$drivermmass,main="Driver Mean PMass")
hist(data$drivermmass,main="Driver Mean PMass")
mean1<-mean(data$drivermmass)
var1<-var(data$drivermmass)
quant<-quantile(data$drivermmass,c(0.05,0.5,0.95))

ts.plot(data$respmmass,main="Resp Mean PMass")
hist(data$respmmass,main="Resp Mean PMass")
mean1<-mean(data$respmmass)
var1<-var(data$respmmass)
quant<-quantile(data$respmmass,c(0.05,0.5,0.95))

ts.plot(data$drivermwidth,main="Driver Mean PWidth")
hist(data$drivermwidth,main="Driver Mean PWidth")
mean1<-mean(data$drivermwidth)
var1<-var(data$drivermwidth)
quant<-quantile(data$drivermwidth,c(0.05,0.5,0.95))

ts.plot(data$respmwidth,main="Resp Mean PWidth")
hist(data$respmwidth,main="Resp Mean PWidth")
mean1<-mean(data$respmwidth)
var1<-var(data$respmwidth)
quant<-quantile(data$respmwidth,c(0.05,0.5,0.95))

ts.plot(data$alphalag/data$betalag,main="Mean Lag")
hist(data$alphalag/data$betalag,main="Mean Lag")
mean1<-mean(data$alphalag/data$betalag)
print("mean of lag distribution")
print(mean1)
var1<-var(data$alphalag/data$betalag)
print(var1)
quant<-quantile(data$alphalag/data$betalag,c(0.05,0.5,0.95))
print(quant)

ts.plot(data$alphalag/data$betalag^2,main="Var Lag")
hist(data$alphalag/data$betalag^2,main="Var Lag")
mean1<-mean(data$alphalag/data$betalag^2)
print("var of lag distribution")
print(mean1)
var1<-var(data$alphalag/data$betalag^2)
print(var1)
quant<-quantile(data$alphalag/data$betalag^2,c(0.05,0.5,0.95))
print(quant)
    
dmassvar<-data[,19]/(data[,19]*data[,18]-data[,20]^2)
rmassvar<-data[,18]/(data[,19]*data[,18]-data[,20]^2)
masscorr<--data[,20]/sqrt(data[,19]*data[,18])
ts.plot(dmassvar,main="Driver PMass Var")
hist(dmassvar,main="Driver PMass Var")
mean1<-mean(dmassvar[])
print("mean of driver mass var distribution")
print(mean1)
var1<-var(dmassvar[])
print(var1)
quant<-quantile(dmassvar[],c(0.05,0.5,0.95))
print(quant)
ts.plot(dmassvar,main="Resp PMass Var")
hist(dmassvar,main="Resp PMass Var")
mean1<-mean(rmassvar[])
var1<-var(rmassvar[])
print(var1)
quant<-quantile(rmassvar[],c(0.05,0.5,0.95))
print(quant)

ts.plot(masscorr,main="PMass Correlation")
hist(masscorr,main="PMass Correlation")    
mean1<-mean(masscorr[])
print("mean of mass corr distribution")
print(mean1)
var1<-var(masscorr[])
print(var1)
quant<-quantile(masscorr[],c(0.05,0.5,0.95))
print(quant)
    
dvarvar<-data[,22]/(data[,21]*data[,22]-data[,23]^2)
rvarvar<-data[,21]/(data[,21]*data[,22]-data[,23]^2)
varcorr<--data[,23]/sqrt(data[,22]*data[,21])
ts.plot(dvarvar,main="Driver PWidth Var")
hist(dvarvar,main="Driver PWidth Var")    
mean1<-mean(dvarvar[])
print("mean of driver var var distribution")
print(mean1)
var1<-var(dvarvar[])
print(var1)
quant<-quantile(dvarvar[],c(0.05,0.5,0.95))
print(quant)
ts.plot(rvarvar,main="Resp PWidth Var")
hist(rvarvar,main="Resp PWidth Var")    
mean1<-mean(rvarvar[])
print("mean of resp var var distribution")
print(mean1)
var1<-var(rvarvar[])
print(var1)
quant<-quantile(rvarvar[],c(0.05,0.5,0.95))
print(quant)

  ts.plot(varcorr,main="PWidth Correlation")
hist(varcorr,main="PWidth Correlation")      
mean1<-mean(varcorr[])
print("mean of mass corr distribution")
print(mean1)
var1<-var(varcorr[])
print(var1)
quant<-quantile(varcorr[],c(0.05,0.5,0.95))
print(quant)

hist(pdata$driverloc,breaks=seq(-100,1600,by=5),main="Driver Pulse Locations")
hist(pdata$resploc,breaks=seq(-100,1600,by=5),main="Response Pulse Locations")

dev.off()

    
